---
name: ci
on:
  push:
    branches: [ snappcloud ]
    tags: [ v* ]
  pull_request:
    branches: [ snappcloud ]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - run: go test -v ./... -covermode=atomic -coverprofile=coverage.out
      - uses: codecov/codecov-action@v1
        with:
          files: coverage.out
  docker:
    name: docker
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@v3
        id: meta
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      - name: Build Docker image using make
        run: |
          make container
        env:
          IMAGE: "ghcr.io/${{ github.repository }}"
          VERSION: ${{ steps.meta.outputs.version }}

      # Push the Docker image to the registry
      - name: Push Docker image
        run: docker push ${{ env.IMAGE }}:${{ env.VERSION }}
        env:
          IMAGE: "ghcr.io/${{ github.repository }}"
          VERSION: ${{ steps.meta.outputs.version }}
